# Generated by Django 4.2.6 on 2023-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dpi', models.FloatField()),
                ('fecha_de_nacimiento', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200)),
                ('receta', models.CharField(max_length=200)),
                ('numero', models.IntegerField(max_length=8)),
                ('otros', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
