# Generated by Django 4.2.6 on 2023-10-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero_de_colegiado', models.IntegerField()),
                ('especialidad', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('otros', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
