# Generated by Django 4.2.6 on 2023-10-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_medico_alter_paciente_dpi_alter_paciente_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
    ]
