# Generated by Django 4.2.6 on 2023-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_rename_nombre_mensajes_nom_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='visita',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
