# Generated by Django 4.2.6 on 2023-11-02 17:19

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_alter_mensajes_numero_alter_paciente_dpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='numero',
            field=models.IntegerField(validators=[clinica.models.longitudnumero]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.IntegerField(validators=[clinica.models.longituddpi]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.IntegerField(validators=[clinica.models.longitudnumero]),
        ),
    ]
