# Generated by Django 4.2.6 on 2023-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_alter_mensajes_numero_alter_paciente_dpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='diagnostico',
            field=models.CharField(max_length=500),
        ),
    ]
