# Generated by Django 4.2.6 on 2023-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_paciente_doctor_alter_medico_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnóstico',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
