# Generated by Django 4.2.6 on 2023-11-04 18:14

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_remove_medico_diagnostico_paciente_diagnóstico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.IntegerField(unique=True, validators=[clinica.models.longituddpi]),
        ),
    ]
