# Generated by Django 4.2.6 on 2023-11-04 18:21

import clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_alter_paciente_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.IntegerField(validators=[clinica.models.longituddpi]),
        ),
    ]
